name: 'install-apt-packages'
description: 'Install necessary apt packages'
inputs:
  java-version:
    description: 'Java version to be installed'
    required: true
runs:
  using: "composite"
  steps:
    - id: install-apt-packages
      run: |
        sudo apt update
        sudo apt -y install \
          python3 \
          python3-pip \
          software-properties-common \
          wget \
          libasio-dev \
          libtinyxml2-dev \
          curl \
          grep \
          ${{ inputs.java-version }}
        jv=$(echo ${{ inputs.java-version }} | sed -r 's/.*-([0-9]*)-.*/\1/g'); jvs=$(update-alternatives --list java | grep "$jv" | head -1); sudo update-alternatives --set java "$jvs"
        jv=$(echo ${{ inputs.java-version }} | sed -r 's/.*-([0-9]*)-.*/\1/g'); jvs=$(update-alternatives --list javac | grep "$jv" | head -1); sudo update-alternatives --set javac "$jvs"
      shell: bash
