name: 'install-apt-packages'
description: 'Install necessary apt packages'
inputs:
  java-version:
    description: 'Java version to be installed'
    required: true
runs:
  using: "composite"
  steps:
    - id: install-apt-packages
      run: |
        sudo apt update
        sudo apt -y install \
          python3 \
          python3-pip \
          software-properties-common \
          wget \
          libasio-dev \
          libtinyxml2-dev \
          curl \
          grep \
          ${{ inputs.java-version }}
      shell: bash
