name: 'fetch-fastddsgen-repos'
description: 'Fetch Fast DDS dependencies'
inputs:
  foonathan_memory_vendor_branch:
    description: 'foonathan_memory_vendor branch to be used'
    required: true
  fastcdr_branch:
    description: 'Fast-CDR branch to be used'
    required: true
  fastdds_branch:
    description: 'Fast-DDS branch to be used'
    required: true
runs:
  using: "composite"
  steps:
    - id: fetch-fastddsgen-repos
      run: |
        cd src
        git clone https://github.com/eProsima/foonathan_memory_vendor.git --branch ${{ inputs.foonathan_memory_vendor_branch }}
        git clone https://github.com/eProsima/Fast-CDR.git --branch ${{ inputs.fastcdr_branch }}
        git clone https://github.com/eProsima/Fast-DDS.git --branch ${{ inputs.fastdds_branch }}
        cd ..
      shell: bash
