# .github/workflows/mirror.yml
name: Mirror
on:
  push:
    branches:
      - '3.3.x'

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror 3.3.x branch to compatible version branches
    strategy:
      fail-fast: false
      matrix:
        dest_branch:
          - '3.x'
    steps:
    - name: Mirror action step
      id: mirror
      uses: eProsima/eProsima-CI/external/mirror-branch-action@v0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: '3.3.x'
        dest: ${{ matrix.dest_branch }}
