# .github/workflows/mirror.yml
on:
  push:
    branches:
      - 'master'
jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror master branch to compatible minor version branches
    strategy:
      fail-fast: false
      matrix:
        dest_branch:
          - '3.3.x'
    steps:
    - name: Mirror action step
      id: mirror
      uses: eProsima/eProsima-CI/external/mirror-branch-action@v0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: 'master'
        dest: ${{ matrix.dest_branch }}
