name: Fast DDS Gen Ubuntu CI

on:
  workflow_dispatch:
    inputs:
      fastddsgen_branch:
        description: 'Fast-DDS-Gen branch to be used'
        required: true
        type: string

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-ci:
    strategy:
      fail-fast: false
      matrix:
        os_image:
          - 'ubuntu-22.04'
        java_version:
          - 'openjdk-11-jdk'
          - 'openjdk-19-jdk'

    uses: ./.github/workflows/reusable-ubuntu-ci.yaml
    with:
      os_image: ${{ matrix.os_image }}
      java_version: ${{ matrix.java_version }}
      fastddsgen_branch: ${{ inputs.fastddsgen_branch || github.ref || 'master' }}
