name: Fast DDS Gen Ubuntu CI (weekly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run at minute 0 on Monday

jobs:
  weekly-ubuntu-ci-2_1_x:
    uses: eProsima/Fast-DDS-Gen/.github/workflows/reusable-ubuntu-ci.yml@2.1.x
    with:
      os-version: 'ubuntu-20.04'
      java-version: 'openjdk-11-jdk'
      label: 'weekly-ubuntu-ci-2.1.x'
      fastddsgen-branch: '2.1.x'
      fastdds-branch: '2.6.x'
      fastcdr-branch: '1.0.x'
      fastdds-python-branch: '1.0.x'
      discovery-server-branch: 'v1.2.1'
      run-build: true
      run-tests: true
      use-ccache: false
